import { PrismaClient } from "@prisma/client";

export type * from "@prisma/client";

const prismaClientSingleton = () => {
  try {
    return new PrismaClient({
      log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
    });
  } catch (error) {
    console.error("Failed to create Prisma Client:", error);
    throw new Error(
      "Prisma Client failed to initialize. Make sure Prisma Client is generated by running 'prisma generate'.",
    );
  }
};

export type ExtendedPrismaClient = ReturnType<typeof prismaClientSingleton>;

// biome-ignore lint/suspicious/noShadowRestrictedNames: Fix this later
declare const globalThis: {
  prismaGlobal: ExtendedPrismaClient;
} & typeof global;

let prisma: ExtendedPrismaClient;

try {
  prisma = globalThis.prismaGlobal ?? prismaClientSingleton();
} catch (error) {
  console.error("Failed to initialize Prisma Client:", error);
  // In production, we should fail fast, but provide a helpful error
  throw new Error(
    "Prisma Client is not available. This usually means Prisma Client was not generated during the build process. Check that 'prisma generate' ran successfully.",
  );
}

export { prisma };

if (process.env.NODE_ENV !== "production") globalThis.prismaGlobal = prisma;
